"""empty message

Revision ID: 042819df57d5
Revises: 
Create Date: 2022-09-15 14:40:40.841254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042819df57d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
