default_language_version:
    python: python3.9
repos:
    - repo: https://github.com/asottile/pyupgrade
      rev: v1.24.1
      hooks:
      - id: pyupgrade
    - repo: https://github.com/ambv/black
      rev: 21.11b0
      hooks:
      - id: black
        exclude: ^venv/
        additional_dependencies: ['click==8.0.4']
        description: 'Black formatting'
        args:
          - "--config"
          - "./pyproject.toml"
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
      - id: trailing-whitespace
        description: 'Trims trailing whitespace'
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        description: 'Makes sure files end in a newline and only a newline.'
      - id: debug-statements
        description: 'Check for debugger imports and breakpoints'
      - id: check-docstring-first
        description: 'Checks for a common error of placing code before the docstring'
      - id: check-merge-conflict
        description: 'Check for files that contain merge conflict strings'
      - id: mixed-line-ending
        description: 'Replaces or checks mixed line endings'
      - id: double-quote-string-fixer
        description: 'Replaces all double quotes to one single quotes'
