[tool.black]
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = true
[tool.coverage.run]
omit = [
    "venv",
    ]

[tool.mypy]
python_version = "3.10"
strict = true
follow_imports = "skip"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = ["ignore::RuntimeWarning"]
